(()=>{
"use strict";
const m=document.getElementById("rdcInteractiveMap");if(!m)return;
const gn=["Governance","Intelligence","Execution","Infrastructure","Business","Quality & Learning"],color=["#6cebd3","#99b2ff","#ffd081","#8cdfb8","#c8a9fb","#ffa9c8"];
const xy=[[240,250],[760,190],[1270,250],[1270,820],[760,895],[240,820]];
const style=document.createElement("style");
style.textContent="#rdcInteractiveMap{width:100%;max-width:100%;min-width:0;background:radial-gradient(ellipse at 50% 48%,#18344d,#081727 79%);border:1px solid #45677a;border-radius:18px;padding:15px;overflow:hidden}#rdcInteractiveMap .fh{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}#rdcInteractiveMap h2{font-size:clamp(20px,2.5vw,27px);margin:0}#rdcInteractiveMap .fsmall{font-size:12px;color:#aec8d8}#rdcInteractiveMap .fmodes{display:flex;flex-wrap:wrap;gap:7px;margin:13px 0}#rdcInteractiveMap button{background:#153247;color:#e7f5ff;border:1px solid #48738a;border-radius:20px;padding:8px 11px;font-size:12px;cursor:pointer}#rdcInteractiveMap button[aria-pressed=true]{background:#1b6a75;border-color:#9aefdf}#rdcInteractiveMap .fstage{width:100%;aspect-ratio:1500/1080;max-height:760px;min-height:300px}#rdcInteractiveMap svg{width:100%;height:100%;display:block}#rdcInteractiveMap .cluster,#rdcInteractiveMap .edge{transition:opacity .3s ease}#rdcInteractiveMap .filabel{cursor:pointer}#rdcInteractiveMap .filabel:hover rect,#rdcInteractiveMap .filabel:focus rect{stroke:#fff;stroke-width:2.8}#rdcInteractiveMap .fdetails{border:1px solid #45687c;border-radius:12px;padding:12px;background:#102a40;font-size:13px;line-height:1.7}#rdcInteractiveMap .fdetails strong{color:#92efdb}@media(max-width:650px){#rdcInteractiveMap .fstage{min-height:260px}}";
document.head.append(style);
m.innerHTML='<div class="fh"><div><h2>RDC L5 · Architecture Flow Map</h2><span class="fsmall">53 Nodes · 6 กลุ่ม · Curved Connections · Mode Highlight</span></div><a style="color:#8befd9;font-size:12px" href="l5-readiness.html">หลักฐาน L5 →</a></div><div class="fmodes" aria-label="เลือกโหมดแผนผัง"></div><div class="fstage"><svg viewBox="0 0 1500 1080" role="img" aria-label="RDC L5 flow network with 53 nodes"></svg></div><div class="fsmall">เส้นโค้งแสดง Logical Flow ระดับสถาปัตยกรรม ไม่ใช่หลักฐาน Live ทุกเส้นทาง · ระบบ Auto Failover ยังไม่รับรอง</div><div class="fdetails">เลือก Mode เพื่อเน้นเส้นทาง และคลิก Node เพื่อดูสถานะจากทะเบียน</div>';
const svg=m.querySelector("svg"),nav=m.querySelector(".fmodes"),info=m.querySelector(".fdetails"),NS="http://www.w3.org/2000/svg";
const legacy=document.querySelector("#architecture .workflow-shell"),oldhead=document.querySelector("#architecture .section-head");if(legacy)legacy.style.display="none";if(oldhead)oldhead.style.display="none";
function el(tag,attrs,parent,text){const e=document.createElementNS(NS,tag);for(const k in attrs)e.setAttribute(k,String(attrs[k]));if(text!=null)e.textContent=text;(parent||svg).append(e);return e}
let clusters=[],edges=[];
const pairs=[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0],[0,5],[2,5]];
function focus(index){clusters.forEach((g,i)=>g.style.opacity=index===-1||i===index?"1":".14");edges.forEach(e=>{const a=+e.dataset.a,b=+e.dataset.b;e.style.opacity=index===-1||a===index||b===index?".72":".05"});nav.querySelectorAll("[data-mode]").forEach(b=>b.setAttribute("aria-pressed",String(+b.dataset.mode===index)))}
function draw(d){svg.replaceChildren();clusters=[];edges=[];const lines=el("g",{});
pairs.forEach(([a,b])=>{const A=xy[a],B=xy[b],mx=(A[0]+B[0])/2,my=(A[1]+B[1])/2;const bend=55*(a%2?1:-1);const path=el("path",{d:"M"+A[0]+" "+A[1]+" Q"+(mx+bend)+" "+(my-bend)+" "+B[0]+" "+B[1],stroke:color[a],"stroke-width":2,fill:"none","stroke-dasharray":"6 9",class:"edge","data-a":a,"data-b":b},lines);edges.push(path)});
xy.forEach(([x,y],i)=>{const p=el("path",{d:"M750 530 Q"+((x+750)/2+(i%2?85:-85))+" "+((y+530)/2)+" "+x+" "+y,stroke:color[i],fill:"none","stroke-width":2,class:"edge","data-a":i,"data-b":i},lines);edges.push(p)});
const hub=el("g",{});el("circle",{cx:750,cy:530,r:104,fill:"#143f55",stroke:"#70e5d5","stroke-width":2.8},hub);el("circle",{cx:750,cy:530,r:116,fill:"none",stroke:"#6cb1bb","stroke-dasharray":"4 11"},hub);el("text",{x:750,y:511,fill:"#f0ffff","text-anchor":"middle","font-size":26,"font-weight":700},hub,"RDC L5");el("text",{x:750,y:542,fill:"#9af8de","text-anchor":"middle","font-size":18},hub,"Orchestrator");el("text",{x:750,y:564,fill:"#d5ecf5","text-anchor":"middle","font-size":12},hub,"PC ↔ NB ↔ Cloud");
gn.forEach((group,i)=>{const [x,y]=xy[i],roles=d.roles.filter(r=>r.group===group),G=el("g",{class:"cluster"});clusters.push(G);
el("ellipse",{cx:x,cy:y,rx:197,ry:175,fill:color[i],opacity:".035"},G);
roles.forEach((r,j)=>{const angle=(-156+312*j/Math.max(1,roles.length-1))*Math.PI/180;const nx=x+190*Math.cos(angle),ny=y+165*Math.sin(angle);const px=x+80*Math.cos(angle),py=y+46*Math.sin(angle);
el("path",{d:"M"+px+" "+py+" Q"+((px+nx)/2+20*Math.sin(angle))+" "+((py+ny)/2-20*Math.cos(angle))+" "+nx+" "+ny,stroke:color[i],"stroke-width":1.2,opacity:".55",fill:"none"},G);
const N=el("g",{class:"filabel",role:"button",tabindex:0,"aria-label":r.name},G);el("rect",{x:nx-79,y:ny-15,width:158,height:30,rx:9,fill:"#142b41",stroke:color[i],"stroke-opacity":".8"},N);el("text",{x:nx,y:ny+4,"font-size":11.8,fill:"#eff8ff","text-anchor":"middle"},N,r.name.length>24?r.name.slice(0,23)+"…":r.name);
function select(){focus(i);info.replaceChildren();const title=document.createElement("strong");title.textContent=r.name+" · "+group;info.append(title);const desc=document.createElement("div");desc.textContent="ทะเบียน: "+(r.status||"UNKNOWN")+" · สถานะนี้ไม่ใช่ Live Telemetry และยังไม่รับรองการทำงานของทุก Node";info.append(desc)}N.addEventListener("click",select);N.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();select()}})});
el("rect",{x:x-104,y:y-40,width:208,height:80,rx:18,fill:"#15344a",stroke:color[i],"stroke-width":2.5},G);
el("text",{x,y:y-7,"font-size":19,"font-weight":700,"text-anchor":"middle",fill:color[i]},G,group);
el("text",{x,y:y+18,"font-size":14,"text-anchor":"middle",fill:"#f0fbff"},G,roles.length+" Nodes");
G.addEventListener("click",e=>{if(e.target.closest(".filabel"))return;focus(i);info.textContent=group+" · "+roles.length+" Nodes · กลุ่มอื่นจางลงเพื่อเน้นเส้นทาง"});
});
["All",...gn].forEach((name,j)=>{const b=document.createElement("button");b.type="button";b.textContent=name==="All"?"All · 53 Nodes":name;b.dataset.mode=j-1;b.addEventListener("click",()=>{focus(j-1);info.textContent=j===0?"ภาพรวม 53 Node":name+" · Focus Mode · แสดงเส้นที่เกี่ยวข้องเด่นขึ้น"});nav.append(b)});
const history=document.createElement("button");history.textContent="History v1.7";history.addEventListener("click",()=>{if(!legacy)return;const show=legacy.style.display==="none";legacy.style.display=show?"":"none";if(oldhead)oldhead.style.display=show?"":"none";history.textContent=show?"ซ่อน History":"History v1.7"});nav.append(history);focus(-1)}
fetch("data/role_registry.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{if(!Array.isArray(d.roles)||d.roles.length!==53)throw Error("53 nodes expected");draw(d)}).catch(e=>info.textContent="ไม่สามารถแสดงแผนผัง: "+e.message);
})();