from pathlib import Path
import re,html
local=Path(r'C:\Users\varachat.num\Documents\Practika-Network-Digital-Twin\internal-enterprise-v2.html')
dest=Path(r'C:\Users\varachat.num\Documents\GitHubPortalWork2\network-diagram\index.html')
original=local.read_text(encoding='utf-8')
style=re.search(r'<style>(.*?)</style>',original,re.S).group(1)
def card(i,title,summary,metrics,action):
    cells=''.join(f'<div class="mini-stat"><span>{html.escape(k)}</span><b>{html.escape(v)}</b><small>{html.escape(s)}</small></div>' for k,v,s in metrics)
    return f'''<section class="card" id="group-{i}"><div class="cardhead"><span class="order">{i}</span><div><h3>{title}</h3><p class="summary">{summary}</p></div></div><div class="viz"><div class="visual-box" style="grid-column:1/-1"><h4>Executive Indicators</h4><div class="mini-stats" style="grid-template-columns:repeat(2,minmax(0,1fr))">{cells}</div></div></div><div class="cardfoot"><span class="statusline">Snapshot 08/10/2026 · รายละเอียดเชิงปฏิบัติการอยู่ในระบบ Internal</span><a class="go" href="{action}">เรียนรู้เพิ่มเติม →</a></div></section>'''
cards=[
('วันนี้ระบบเป็นอย่างไร','ผล Scan พร้อมใช้สำหรับตัดสินใจ แต่การตรวจสถานะบริการและความพร้อมใช้งานต้องอาศัยข้อมูล Monitoring เพิ่มเติม',[('Full Scan','100%','baseline complete'),('Live nodes','477','discovered'),('Deep nodes','209','focus'),('Critical paths','18/18','zero-loss sample')]),
('Risk & Priority Actions','จัดลำดับความเสี่ยงแบบ P0–P2 ให้ผู้รับผิดชอบจัดทำแผนแก้ไข ทดสอบผลกระทบ และแผนย้อนกลับก่อนเปลี่ยนระบบ',[('Risk','Watch','tracked findings'),('Priority','P0/P1','review first'),('Legacy','Review','lifecycle'),('Recovery','Plan','owner + backup')]),
('Network Architecture & Physical Twin','Logical Twin พร้อมใช้งาน แต่การยืนยัน Port, Uplink, AP, VLAN และ Firewall ต้องมีสิทธิ์ Management แบบ Read-only',[('Physical Truth','0/5','confirmed'),('Partial','4/5','evidence incomplete'),('Auth Gate','1/5','pending'),('Core','20','full-port profiles')]),
('Server / Application / Backup','รวมบริบท Server, Application, Backup, Restore และความสัมพันธ์ของบริการ เพื่อวิเคราะห์ผลกระทบเมื่อส่วนใดส่วนหนึ่งล้มเหลว',[('Health','Gap','needs telemetry'),('Backup','Review','restore evidence'),('Service Map','Improve','dependency'),('Capacity','Watch','trend required')]),
('Scan Coverage & Evidence','การค้นพบไม่ใช่การยืนยันโครงสร้างจริง ต้องแยก Confirmed, Observed, Candidate และ Unknown ทุกครั้ง',[('Full Scan','100%','4,957,500 checks'),('Coverage','477','baseline nodes'),('Deep scope','209','selected'),('Truth','Pending','physical mapping')]),
('Subnet / Device / Inventory','รักษาความถูกต้องของข้อมูลสินทรัพย์ เชื่อม Owner, ประเภทอุปกรณ์, สถานที่ และวงจรอายุโดยเก็บข้อมูลระบุตัวตนใน Internal',[('Assets','477','baseline'),('Owner','Review','data quality'),('License','16','groups identified'),('Expiry','Gap','needs owners')])
]
body='''<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Practika Network Digital Twin — Executive Home</title><style>'''+style+'''
.publicnav{display:flex;gap:9px;flex-wrap:wrap;margin:18px 0}.publicnav a{background:#e8f2ff;color:#174c88;border:1px solid #afcceb;padding:10px 15px;border-radius:11px;text-decoration:none;font-weight:800;font-size:13px}.publicnav a.primary{background:#245fa8;color:#fff}.palert{padding:12px 16px;background:#f2f7ff;border:1px solid #b9cee6;border-radius:12px;margin:15px 0;color:#425d7c}.story .flow .step{min-height:96px}@media(max-width:700px){.kpis{grid-template-columns:repeat(2,1fr)}.publicnav a{flex:1;text-align:center}}
</style></head><body><div class="wrap"><div class="hero"><div><div class="eyebrow">EXECUTIVE · PUBLIC-SAFE · NETWORK OPERATIONS HOME</div><h1>Practika Network Digital Twin</h1><p class="sub">หน้าแรกหลักตามรูปแบบ <b>Internal Enterprise V2</b> • สรุปสถานะ → ความเสี่ยง → สถาปัตยกรรม → Server / Backup → Evidence → Inventory พร้อมแผนผัง Interactive Mind Map สำหรับเรียนรู้ความสัมพันธ์</p></div><span class="badge">Public-safe · Read-only Snapshot</span></div>
<nav class="publicnav"><a class="primary" href="./">Executive Home</a><a href="./mindmap.html">Interactive Mind Map ↗</a><a href="./executive-cockpit.html">Executive Cockpit</a><a href="../">Project Portal</a></nav><div class="palert"><b>ขอบเขตข้อมูล:</b> หน้าเว็บนี้คงโครงสร้างหลักของ Local Executive Home แต่แสดงเฉพาะข้อมูลที่เหมาะกับเว็บสาธารณะ ไม่มีข้อมูล IP, Hostname, Port/Policy รายเครื่อง หรือรายละเอียดช่องโหว่ ข้อมูลเชิงลึกดูได้จาก Internal Gateway ที่ได้รับอนุญาตเท่านั้น (Snapshot 8 ต.ค. 2569)</div>
<div class="kpis">'''
for label,val,sub in [('Full Scan','100%','ตรวจครบ baseline'),('Known Live','477','อุปกรณ์ที่ตรวจพบ'),('Deep Nodes','209','deep observe'),('Core profiles','20','full-port'),('Critical path','18/18','zero loss sample'),('Physical Truth','0/5','confirmed'),('Current risks','Review','action priorities'),('Data Freshness','08/10','snapshot')]:
    body+=f'<a class="kpi kpi-link" href="#groups"><span>{label}</span><b>{val}</b><small>{sub} →</small></a>'
body+='''</div><section class="reaudit-cockpit"><div class="rcp-head"><div><div class="eyebrow">RE-AUDIT · VERIFIED SNAPSHOT · 08/10/2026</div><h2>Executive Network Cockpit · จาก “ระบบใช้ได้ไหม” สู่ “บริหารความเสี่ยงได้หรือยัง”</h2><p>แยกสถานะการดำเนินงาน ความเสี่ยง ความจุ หลักฐาน Physical Topology และ Governance เพื่อให้ผู้บริหารเห็นความสำคัญตามลำดับ</p></div><span class="rcp-stamp">Read-only · Evidence First</span></div><div class="rcp-story">'''
for i,(t,cls,s) in enumerate([('Operate','good','Critical-path measured sample: 18/18 zero packet loss'),('Protect','risk','Review aging technology, exposure and ownership'),('Optimize','watch','Monitor capacity and wireless experience'),('Prove','gap','Physical topology: 0/5 confirmed'),('Govern','gap','Complete monitoring and license ownership')],1):
    body+=f'<div class="rcp-step {cls}"><span>{i:02}</span><b>{t}</b><p>{s}</p></div>'
body+='''</div><div class="rcp-grid"><div class="rcp-panel"><h3>Operate</h3><div class="rcp-metrics"><div class="rcp-metric"><span>Full Scan</span><b>100%</b></div><div class="rcp-metric"><span>Measured Critical Paths</span><b>18/18</b></div></div></div><div class="rcp-panel"><h3>Protect & Optimize</h3><p>Security lifecycle, management hardening, service continuity and capacity governance remain prioritized action themes.</p></div><div class="rcp-panel"><h3>Prove & Govern</h3><div class="rcp-metrics"><div class="rcp-metric"><span>Physical Confirmed</span><b>0/5</b></div><div class="rcp-metric"><span>License Groups</span><b>16</b></div></div></div></div><div class="rcp-legend"><span>CONFIRMED</span><span>OBSERVED</span><span>CANDIDATE</span><span>UNKNOWN</span></div></section>
<section class="story"><h2>Business Flow — เริ่มดูจากอะไร</h2><p>คลิกแต่ละหัวข้อเพื่อเจาะส่วนที่เกี่ยวข้อง หรือเปิด Mind Map เพื่อเห็นความสัมพันธ์ข้ามกลุ่ม</p><div class="flow">'''
for i,t in enumerate(['สถานะวันนี้','Risk & Action','Architecture','Server / Backup','Coverage','Inventory'],1):
    body+=f'<a class="step" href="#group-{i}" style="text-decoration:none;color:inherit"><div class="n">{i:02}</div><b>{t}</b><small>คลิกดู Executive Summary →</small></a>'
body+='</div></section><div class="grid" id="groups">'
for i,(title,summary,metrics) in enumerate(cards,1):
    body+=card(i,title,summary,metrics,'./mindmap.html')
body+='''</div><section class="story"><h2>Interactive Mind Map · กลุ่มการเรียนรู้</h2><p>Mind Map เป็นกลุ่มเสริมในเว็บหลัก ช่วยเปิดเผยความสัมพันธ์ระหว่าง Discovery, Operate, Protect, Optimize, Physical Twin และ Govern</p><p><a class="go" href="./mindmap.html">เปิด Mind Map แบบโต้ตอบ →</a></p></section><div class="foot"><span>Practika Network Digital Twin · Public-safe adaptation of Local Executive V2 · 08/10/2026</span><span><a href="../">กลับ Portal</a></span></div></div></body></html>'''
dest.write_text(body,encoding='utf-8')
portal=Path(r'C:\Users\varachat.num\Documents\GitHubPortalWork2\index.html')
s=portal.read_text(encoding='utf-8').replace('https://popvarachat.github.io/network-diagram/executive-cockpit.html','https://popvarachat.github.io/network-diagram/')
portal.write_text(s,encoding='utf-8')
print('PUBLIC_MAIN_BYTES',dest.stat().st_size,'HAS_MINDMAP', 'mindmap.html' in body,'PRIVATE_IP_MATCH',bool(re.search(r'\b(?:10|172|192)\.\d+\.\d+\.\d+\b',body)))
